### ISSUE TITLE
Brakujący plik JPG

### ISSUE THREAD

**Issue by robertu** [vilible/django-tutorial#1]
![image](https://user-images.githubusercontent.com/1024969/225230806-d45aed21-7a33-485e-a2ed-2506327cbc6e.png)

**Comment by vilible** [comment]
Plik JPG znajduje się w part-6/polls/static/polls/images. Po sklonowaniu repozytorium na dysk wszystko działa poprawnie, a zdjęcie jest na swoim miejscu.
